################################################################################
# > Playbook used to configure Drone CI CD server
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Configure Drone CI/CD
  hosts: drone
  become: yes

  roles:
    - role: common
      tags: ['common']

    - role: docker
      tags: ['docker']

    - role: drone
      tags: ['drone']

