################################################################################
# > Playbook used to configure Drone CI CD server
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- name: Configure the WebSever to run the SPA
  hosts: web
  become: yes

  roles:
    - role: Lowess.common
      tags: ['common']

    - role: Lowess.ngrok
      tags: ['ngrok']

    - role: Lowess.nginx
      tags: ['nginx']

    - role: spa
      tags: ['spa']
